name: Go CI

on:
  push:
    branches: [ "feature/dev-ops" ]
  pull_request:
    branches: [ "feature/dev-ops" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: log lowercase repo name
      run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.REPO }}:latest 